### ISSUE TITLE
No files match the pattern: src/js/reducers/config.js

### ISSUE THREAD

**Issue by basilesportif** [urbit/create-landscape-app#40]
To reproduce:
* cloned this repo
* ran `npm install`
* ran `npm start`
* gave app name as `mylandscape` and pointed to `/Users/blah/code/urbit/urbit-v0.10.5-darwin/zod/home` which has a mounted `%home` desk.

Full output
```
What's the name of your application? Lowercase and no spaces, please.: mylandscape
Is your app just a tile, or a full application? (tile/full): full
Where is your Urbit pier's desk located? For example, /Users/dev/zod/home: /Users/blah/code/urbit/urbit-v0.10.5-darwin/zod/home
All done! Happy hacking.
Error: No files match the pattern: src/js/reducers/config.js
    at /Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/lib/helpers/glob-async.js:27:23
    at f (/Users/blah/code/urbit/mylandscape/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:210:5)
    at Glob._finish (/Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/node_modules/glob/glob.js:197:8)
    at done (/Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/node_modules/glob/glob.js:688:12)
    at /Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/blah/code/urbit/mylandscape/node_modules/replace-in-file/node_modules/glob/glob.js:764:12)
[ { file: '.urbitrc', hasChanged: true } ]
```

**Comment by matildepark** [comment]
Fixed in 7b46e2a4a1dfd85317d217ea21ff0a95b7f722aa, sorry about that.
