### ISSUE TITLE
TypeError in landscape home page on fake ship

### ISSUE THREAD

**Issue by pilwex-migsun** [urbit/create-landscape-app#47]
After running a fresh app created by CLA on a fake ship (`|start %appname`), an error appears in home page in landscape. 

![Screenshot from 20](https://user-images.githubusercontent.com/58215101/96018321-63861600-0e4b-11eb-9de4-8885de4b06eb.png)

Also, the icons in app's page do not show correctly.

![Screenshot from 2020](https://user-images.githubusercontent.com/58215101/96018290-58cb8100-0e4b-11eb-9065-b5f1b22a8872.png)

output:
> TypeError: No[e] is not a function
    at Icon (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:364:108223)
    at Za (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:57929)
    at gs (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:104168)
    at cl (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:96716)
    at sl (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:96641)
    at Qs (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:93671)
    at http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:45313
    at t.unstable_runWithPriority (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:327:3844)
    at Bi (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:45022)
    at Vi (http://localhost:8081/~landscape/js/bundle/index.4c5a7f72912cc668f0e5.js:319:45258)

system:
Linux64
MacOS
urbit 0.10.8

To reproduce:
- clone and save CLA,
- run `sudo npm install`
- run  `sudo npm install --save @tlon/indigo-light styled-components styled-system react react-dom @reach/disclosure @reach/menu-button @reach/tabs markdown-to-jsx formik`
- run `sudo npm start`
- run `sudo npm run serve`
- run `|commit %home`
- run `|start %appname`
- open landscape page on browser

**Comment by matildepark** [comment]
This isn't a CLA bug; it's a bug with urbit/urbit and how third-party apps function on the current boot pill.

In indigo-react, the `Icon` component now crashes if passed no key, I believe; on livenet, this is fixed in https://github.com/urbit/urbit/commit/a2fbf8c51c0914b212bf74d1fcff7195d914e2fa. The boot pill precedes this commit, so it retains the bug. It only affects ships with third-party applications. 

If you boot your fake ship with the current `master` branch's `pkg/arvo` this issue is resolved. You can also just directly go to `http://localhost:9000/~appname` to sidestep this.

eg. `./urbit -F zod -B "bin/solid.pill" -A "pkg/arvo"` from the urbit repo directory, assuming `git lfs install` and `git lfs pull` have been run to get the pill blobs.
